export const PRESS_LINK = "PRESS_LINK";
export const START_EDITING = "START_EDITING";
export const END_EDITING = "END_EDITING";
export const GET_MENU = 'GET_MENU';

// export const GET_ALL_JENIS_NILAI_PRESENTASI = 'GET_ALL_JENIS_NILAI_PRESENTASI';
// export const SET_JENIS_NILAI_PRESENTASI = 'SET_JENIS_NILAI_PRESENTASI';
export const GET_HASIL_NILAI_PRESENTASI = 'GET_HASIL_NILAI_PRESENTASI';


