export const PRESS_LINK = "PRESS_LINK";

export const GET_API_URL= 'GET_API_URL';

export const START_EDITING = "START_EDITING";
export const END_EDITING = "END_EDITING";

export const DELETE_BARANG = 'DELETE_BARANG';
export const GET_ALL_BARANG = 'GET_ALL_BARANG';
export const STORE_BARANG = 'STORE_BARANG';
export const UPDATE_BARANG = 'UPDATE_BARANG';

export const CURRENT_DATA = 'CURRENT_DATA';
export const LOADING_PAGE = 'LOADING_PAGE';
export const GET_MENU = 'GET_MENU';
// export const GET_ALL_KANTOR = 'GET_ALL_KANTOR';
export const GET_ALL_PEGAWAI = 'GET_ALL_PEGAWAI';
export const SET_PAGE = 'SET_PAGE';
export const SET_CURRENT_KONTAINER = 'SET_CURRENT_KONTAINER';
export const SET_CURRENT_KEMASAN = 'SET_CURRENT_KEMASAN';
export const SET_DATA_PAGE = 'SET_DATA_PAGE';
export const SET_SHOW_FORM = 'LOADING_FORM';

//AP
export const GET_TABLE_DATA = 'GET_TABLE_DATA';
export const SET_AP_LOADING = 'SET_AP_LOADING';
export const SET_AP_FAILED = 'SET_AP_FAILED';
export const SET_AP_SUCCESS = 'SET_AP_SUCCESS';
export const SET_CATATAN_LIST = 'SET_CATATAN_LIST';
export const SET_CURRENT_PROSES = 'SET_CURRENT_PROSES';

// daftar izin lartas
export const SET_DAFTAR_IZIN_LARTAS_FAILED = 'SET_DAFTAR_IZIN_LARTAS_FAILED';
export const SET_DAFTAR_IZIN_LARTAS_LOADING = 'SET_DAFTAR_IZIN_LARTAS_LOADING';
export const SET_DAFTAR_IZIN_LARTAS_SUCCESS = 'SET_DAFTAR_IZIN_LARTAS_SUCCESS';

// histori keputusan
export const SET_HISTORY_KEPUTUSAN_FAILED = 'SET_HISTORY_KEPUTUSAN_FAILED';
export const SET_HISTORY_KEPUTUSAN_LOADING = 'SET_HISTORY_KEPUTUSAN_LOADING';
export const SET_HISTORY_KEPUTUSAN_SUCCESS = 'SET_HISTORY_KEPUTUSAN_SUCCESS';

export const SET_DETAIL_DOKUMEN = 'SET_DETAIL_DOKUMEN';

// pencarian AP
export const SET_CARI_AP_LOADING = 'SET_AP_LOADING';
export const SET_CARI_AP_FAILED = 'SET_AP_FAILED';
export const SET_CARI_AP_SUCCESS = 'SET_AP_SUCCESS';

export const GET_TABLE_DATA_CARI = 'GET_TABLE_DATA_CARI';

// SETTING
export const GET_DATA_HANGGAR_LOADING = 'GET_DATA_HANGGAR_LOADING';
export const GET_DATA_HANGGAR_SUCCESS = 'GET_DATA_HANGGAR_SUCCESS';
export const GET_DATA_HANGGAR_FAILED = 'GET_DATA_HANGGAR_FAILED';
export const GET_DATA_HANGGAR = 'GET_DATA_HANGGAR';
export const SET_DATA_PERUSAHAAN_SELECTED = 'SET_DATA_PERUSAHAAN_SELECTED';

// ACTION : PERBAIKAN
export const PERBAIKAN_SET_RANGE_DATE = 'PERBAIKAN_SET_RANGE_DATE';
export const PERBAIKAN_SET_RELOAD = 'PERBAIKAN_SET_RELOAD';
export const PERBAIKAN_SET_LOADING = 'PERBAIKAN_SET_LOADING';
export const PERBAIKAN_SET_DATA_PEREKAMAN = 'PERBAIKAN_SET_DATA_PEREKAMAN';

export const GET_ALL_JENIS_NILAI_PRESENTASI = 'GET_ALL_JENIS_NILAI_PRESENTASI';
export const SET_JENIS_NILAI_PRESENTASI = 'SET_JENIS_NILAI_PRESENTASI';
