export default {
    refFasilitas : [
        {kdRef : "1", nmRef: "AEO"},
        {kdRef : "2", nmRef: "MITA"},
        {kdRef : "3", nmRef: "PLB"},
        {kdRef : "4", nmRef: "TPB"},
        {kdRef : "5", nmRef: "KITE"},
        {kdRef : "6", nmRef: "KITE IKM"},
    ],
    refJnsContaner : [
        {kdRef : "LCL", nmRef: "LCL"},
        {kdRef : "FCL", nmRef: "FCL"},
    ],
    refRedress : [
        {kdRef : "Y", nmRef: "on"},
        {kdRef : "N", nmRef: "off"},
    ],
    refUkuranContainer : [
        {kdRef : "20", nmRef: "20 Feet"},
        {kdRef : "40", nmRef: "40 Feet"},
        {kdRef : "45", nmRef: "45 Feet"},
    ],
    refJnsBarangDok : [
        {kdRef : "0", nmRef: "Tidak Aktif"},
        {kdRef : "1", nmRef: "Aktif"},
    ],
    refJnsPengangkutan : [
        {kdRef : "1", nmRef: "Laut"},
        {kdRef : "2", nmRef: "Kereta Aoi"},
        {kdRef : "3", nmRef: "Darat"},
        {kdRef : "4", nmRef: "Udara"},
        {kdRef : "5", nmRef: "Pos"},
        {kdRef : "6", nmRef: "Multi Moda"},
        {kdRef : "7", nmRef: "Instalasi"},
        {kdRef : "8", nmRef: "Perairan"},
        {kdRef : "9", nmRef: "Lainnya"},
    ],
    refBuPenerima : [],
    refJnsRulesetP2 : [],
    refProfilImportir : [],
    refProfilPjt : [],
    refNegara : [],
    refValuta : [],
    refImportir : [],
    refPemasok : [],
    refKppbc : [],
    refKdKanwil : [],
    refKdKppbc : [],
    refPelabuhanBongkar : [],
    refPelabuhanMuat : [],
    refPelabuhanTransit : [],
    refPPjk : [],
    refPjt : [],

};